### ISSUE TITLE
Psp problem

### ISSUE THREAD

**Issue by InigoMarin** [danielgtaylor/arista#38] opened 2010-10-07 09:18 UTC
Arista 0.9.5
Ubuntu 10.10

Psp says unsupported format.

**Comment by Devi710** [comment] 2011-01-30 00:55
I am having the same problem. 

It was fine when I was using Ubuntu 10.4 32bit, but now I am using Ubuntu 10.10 64bit, and the video always comes up as "unsupported format" on the PSP.

The converted files will play on my PC, but not on the PSP. I've converted several different formats, avi, mov, wmv, all with the same result. 

Is there a PPA with a newer version where this is fixed?

**Comment by Devi710** [comment] 2011-01-30 01:22
The problem is the same in both version 0.9.5, and the latest, 0.9.6.

**Comment by matt2000** [comment] 2011-04-09 17:05
Duplicate issue of https://github.com/danielgtaylor/arista/issues/#issue/49.

Framerate in preset needs to be set to 30.

**Comment by danielgtaylor** [comment] 2011-06-16 16:51
This should be fixed in trunk.

**Closed as completed by danielgtaylor** 2011-06-16 16:51 UTC
