### ISSUE TITLE
-5:11 remaining

### ISSUE THREAD

**Issue by monreal** [danielgtaylor/arista#29] opened 2010-08-20 17:35 UTC
After a test transcode from DVD, the remaining time suddenly was at -5.11. The transcoded file was complete but arista did not view the job as "done".

**Comment by danielgtaylor** [comment] 2010-09-02 20:43
Can this be consistently reproduced? It may be an issue in the underlying GStreamer bins that decode DVDs. This will likely be hard to reproduce for me and to track down...

**Comment by monreal** [comment] 2010-09-02 20:49
No, I have only seen this once yet... in case I ever see it again: what kind of information would be useful?

gstreamer-0.10.30-1.fc13.i686
gstreamer-plugins-base-0.10.30-1.fc13.i686
gstreamer-plugins-good-0.10.24-1.fc13.i686
gstreamer-plugins-bad-0.10.19-1.fc13.i686
gstreamer-plugins-bad-free-0.10.19-1.fc13.i686
gstreamer-plugins-bad-nonfree-0.10.18-1.fc13.i686
gstreamer-plugins-ugly-0.10.15-1.fc13.i686

**Comment by danielgtaylor** [comment] 2011-06-16 20:57
Since this appears to have been a one-time event I'm closing for now. If you can get it to happen more (and preferably consistently) then please reopen!

**Closed as completed by danielgtaylor** 2011-06-16 20:57 UTC
Labels: NeedsInfo
