### ISSUE TITLE
audio sync and wrong format

### ISSUE THREAD

**Issue by guiodic** [danielgtaylor/arista#12] opened 2010-06-07 23:29 UTC
Converting from ogv to h264 (computer/h264) have a strange behaviour:

1) audio is heavy out of sync
2) strangely, audio becomes aac but video codec is still theora according totem but it is avc (then h254 I figure) according vlc!

I use arista from git with latest gstreamer packeges from gst dev ppa on ubuntu lucid.

**Comment by danielgtaylor** [comment] 2010-06-08 01:23
Can you provide a sample file that causes this behavior?

**Comment by guiodic** [comment] 2010-06-08 17:01
I used this one: http://ia331209.us.archive.org/0/items/Patent_Absurdity/Patent_Absurdity_LQ_350kbit.ogv

**Comment by danielgtaylor** [comment] 2010-06-10 03:32
Thanks for the sample. It appears the muxer is copying metadata from the demuxer and so the output file is tagged as having been encoded with libtheora and such, but FFmpeg and MediaInfo both see the file as it really is (H.264/AAC in MP4). It only seems to be GStreamer-based stuff reporting it as theora. I'll mention it upstream and see what they have to say tomorrow.

The a/v sync issue I can't reproduce using the latest development GStreamer release (see https://launchpad.net/~gstreamer-developers/+archive/ppa ) so I think we can assume that bug was fixed upstream and need to wait for Ubuntu to incorporate it or just use the PPA I linked.

**Comment by guiodic** [comment] 2010-06-10 21:49
about a/v sync... well I use that repository....

**Comment by danielgtaylor** [comment] 2010-06-11 03:13
Do you also notice the a/v sync issue when playing back in a non-GStreamer player like e.g. VLC? The output seems in sync to me...

**Comment by guiodic** [comment] 2010-06-12 23:28
mm I tried with today snapshot form git. The first isse is still here, the second is solved.

**Comment by dooglio** [comment] 2011-02-28 18:28
I have the same setup (using the gstreamer repo) and when I attempt to transform a wmv movie to a m4v (for my Apple iPod) the audio comes out all choppy.

Here is the source:
http://www.dwad.net/episodes/178%20Might%20of%20the%20Starry%20Sea%2005.wmv

Here is the result:
http://www.dooglio.net/video/178_Might_of_the_Starry_Sea_05.m4v

The video seems synced fine, but the audio has a choppy "pulse" that is really annoying...

**Comment by dooglio** [comment] 2011-02-28 18:29
Oh, and I'm using the git trunk for arista, running the arista-gtk interface.

**Comment by danielgtaylor** [comment] 2011-03-02 15:11
This seems to be an upstream GStreamer issue.

**Comment by dooglio** [comment] 2011-03-02 18:46
Ah man, bummer. Hey at least it's not your code Daniel. Thanks for your attention to this, and thanks for a nice little project!

**Comment by danielgtaylor** [comment] 2011-06-16 21:06
I believe issue 24 is a duplicate of this one. Upstream bug is https://bugzilla.gnome.org/show_bug.cgi?id=652765

**Comment by danielgtaylor** [comment] 2011-06-17 15:13
Apparently this was not a dupe of issue #24. Instead, it has to do with the audiorate element and sloppy WMV input. Should be fixed in f1ef53d by setting a tolerance on the audiorate element.

**Closed as completed by danielgtaylor** 2011-06-17 15:13 UTC
Labels: Confirmed
