### ISSUE TITLE
arista-nautilus.py should be byte-compiled

### ISSUE THREAD

**Issue by alessio** [danielgtaylor/arista#14] opened 2010-06-13 18:12 UTC
Installing arista-nautilus.py as a data file prevents its bite-compilation.
After applying the following patch the nautilus extensions won't be installed in the proper path but you can workaround that by creating a symbolic link under /usr/lib/nautilus/extensions-2.0/python/.

```
Author: Alessio Treglia <alessio@debian.org>
Description: Don't install arista-nautilus.py as a data file, it must be
 byte-compiled first.

---
 setup.py |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

--- arista.orig/setup.py
+++ arista/setup.py
@@ -18,7 +18,6 @@ data_files = [
     (os.path.join("share", "doc", "arista"), [
         "README.md", "LICENSE", "AUTHORS"
     ]),
-    (os.path.join("lib", "nautilus", "extensions-2.0", "python"), ["arista-nautilus.py"]),
 ]

 for (prefix, path) in [("arista", "presets"), 
@@ -83,6 +82,7 @@ Note: WebM support requires at least GSt
     scripts = [
         "arista-gtk",
         "arista-transcode",
+        "arista-nautilus.py",
     ],
     data_files = data_files,
     requires = [ 
```

**Comment by alessio** [comment] 2010-06-13 18:13
The patch is not displayed well, please follow this link:
http://git.debian.org/?p=collab-maint/arista.git;a=blob;f=debian/patches/01-bytecompile_nautilus_extension.patch;h=48b7196be0ef77c23b04957167197cb68e481d9d;hb=HEAD

**Comment by danielgtaylor** [comment] 2010-06-14 00:12
The arista-nautilus.py script is actually not executable on its own (it imports a module that only exists inside of a running instance of Nautilus itself), so I'd rather not install it as an executable script.

What about using this?
- http://docs.python.org/library/py_compile.html

We can manually byte-compile just that one file in setup.py. Would that work as a fix for this issue?

**Comment by alessio** [comment] 2010-06-14 05:10
Yes, I know that it's not runnable (in fact I don't put the script into the python path) but it's a module anyway and on Debian systems, after installing modules, they should be byte-compiled.

Although I've never used py_compile before it may be a workaround but please note that with my patch arista-nautilus.py doesn't get installed as module callable from the interpreter ('import arista-nautilus' doesn't work anyway) too.

**Comment by danielgtaylor** [comment] 2010-06-17 21:58
The problem is that the file is installed as if it were a shell script, so a user can try to run it from the terminal and it will fail 100% of the time, unable to import 'nautilus'.

I don't see an easy way to force the byte-compiling of data files in distutils, so I'm not sure what a better solution is yet.

**Comment by alessio** [comment] 2010-06-18 11:52
A solution may be writing a Makefile to wrap the setup.py script.

**Comment by danielgtaylor** [comment] 2010-06-18 15:55
This should be fixed in 6322c5b55cb93979cebc2e4fd80e6974df82ca2e. Please test and confirm. It now byte-compiles any .py files found in the data_files tuple after installing them with a custom install command passed to distutils setup(...).

**Comment by alessio** [comment] 2010-06-20 19:20
I'll do some testing ASAP, thanks.

**Comment by solsticedhiver** [comment] 2010-12-03 10:53
this does not work !

when running python2 setup.py install --prefix=/usr --root=${pkgdir}
$pkgdir is here /home/solstice/abs/arista-devel/pkg
I get this error:

```
[...]
creating /home/solstice/abs/arista-devel/pkg/usr/share/locale/zh_TW/LC_MESSAGES
copying locale/zh_TW/LC_MESSAGES/arista.mo -> /home/solstice/abs/arista-devel/pkg/usr/share/locale/zh_TW/LC_MESSAGES
creating /home/solstice/abs/arista-devel/pkg/usr/share/locale/templates
copying locale/templates/arista.pot -> /home/solstice/abs/arista-devel/pkg/usr/share/locale/templates
byte-compiling /usr/lib/nautilus/extensions-2.0/python/arista-nautilus.py
error: /usr/lib/nautilus/extensions-2.0/python/arista-nautilus.pyc: Permission denied
```

so /usr/lib is hard-coded and it is not possible to compile while making a package using a root other than /

**Comment by DimStar77** [comment] 2010-12-27 15:16
I applied this chunk in plus, which allows me to specify --root and still have th .py compiled:

# Index: arista-0.9.6/setup.py

--- arista-0.9.6.orig/setup.py
+++ arista-0.9.6/setup.py
@@ -50,7 +50,7 @@ class AristaInstall(install_data):
         for path, fnames in data_files:
             for fname in fnames:
                 if fname.endswith(".py"):
-                    full = os.path.join(sys.prefix, path, fname)
-                    full = os.path.join(self.root + sys.prefix, path, fname)
                   print "byte-compiling %s" % full
                   py_compile.compile(full)

**Comment by DimStar77** [comment] 2010-12-27 15:50
Pasting a patch here is really horrible... so:
see https://github.com/danielgtaylor/arista/pull/54 (Pull request 54)

**Closed as completed** 2010-12-27 16:41 UTC
Labels: ConfirmFix
