### ISSUE TITLE
Choppy playback on iPad

### ISSUE THREAD

**Issue by LinusU** [danielgtaylor/arista#79] opened 2011-02-14 15:50 UTC
Whenever I convert video with the iPad presets the resulting file plays nice in mplayer/totem. However when I try to play it in Quicktime (on Mac) or on the iPad it plays really choppy. This occurs regardless if I choose low or medium quality.

I have tried with many different files and it's always the same result. However I know that I have managed to convert some files a long time ago on another computer.

**Comment by AkeemMcLennon** [comment] 2011-02-14 19:11
I had a similar issue with a custom preset I created for the videos on my website.

I suspect that this to do with a bug in gstreamer that I found earlier at https://bugzilla.gnome.org/show_bug.cgi?id=624212

Presumably, this bug has already been resolved in the most recent release of gstreamer, but it still seems to be present in the version that ships with most distributions.  In the meantime, I have disabled bframes in my own preset as a workaround to this issue, but this is only a temporarily solution to the problem.

**Comment by LinusU** [comment] 2011-02-14 23:22
I updated my gstreamer with the natty packages but the issue is still occurring.

$ gst-launch-0.10 --version

gst-launch-0.10 version 0.10.32
GStreamer 0.10.32

**Comment by danielgtaylor** [comment] 2011-06-14 13:27
Have you confirmed this issue with Ubuntu 11.04?

**Comment by AkeemMcLennon** [comment] 2011-06-17 03:23
I do not own an iPad, but I noticed this issue on OS X machines as well.  I should be able to test it out within the next few days.

**Closed as completed** 2011-06-17 14:07 UTC
Labels: NeedsInfo
